spring:
    redis:
        # Redis服务器地址
        host: 192.168.198.129
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: vv123456
        #集群环境打开下面注释，单机不需要打开
        cluster:
          #集群信息
          nodes: 192.168.198.129:7001,192.168.198.129:7002,192.168.198.129:7003
          #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
          maxRedirects: 3
        pool:
           # 连接池最大连接数（使用负值表示没有限制）
           max-active: 8
           # 连接池中的最大空闲连接
           min-idle: 0
           # 连接池最大阻塞等待时间（使用负值表示没有限制）
           max-wait: -1
           # 连接池中的最小空闲连接
           max-idle: 8
        # 连接超时时间（毫秒）
        timeout: 20
